# Generated by Django 2.1.1 on 2018-10-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='a',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='b',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
